"""add email column to signup

Revision ID: 918acbc61f1c
Revises: a5b876185891
Create Date: 2024-08-21 08:30:47.651393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918acbc61f1c'
down_revision = 'a5b876185891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
