"""add serial number to sensor db

Revision ID: ecabb73c8a8b
Revises: 918acbc61f1c
Create Date: 2024-08-30 14:44:45.947107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecabb73c8a8b'
down_revision = '918acbc61f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_column('serial')

    # ### end Alembic commands ###
